### ISSUE TITLE
Python Scripting templates do not return pandas Dataframe

### ISSUE THREAD

**Issue by bicklem** [knime-mpicbg/knime-scripting#116]
I am creating Python Scripting snippets for image analysis, but the pyOut DataFrame throws an error when converting to csv
ERROR Python Snippet       4:520      Execute failed: Error in processing: Traceback (most recent call last):
  File "/private/var/folders/52/2b38vy8j1nl56kcrn426xzrm0000gn/T/SVmMQ4_analyze_3818067234225383873.py", line 148, in <module>
    write_csv(r"/private/var/folders/52/2b38vy8j1nl56kcrn426xzrm0000gn/T/SVmMQ4_pyOut_python2knime_11741287442358462654.csv",pyOut)
  File "/private/var/folders/52/2b38vy8j1nl56kcrn426xzrm0000gn/T/SVmMQ4_analyze_3818067234225383873.py", line 79, in write_csv
    pyOut.to_csv(f, header=False, date_format='%Y-%m-%dT%H:%M:%S.%f', line_terminator = '\r\n', escapechar = "\\", doublequote=False, quoting=csv.QUOTE_NONNUMERIC)
TypeError: to_csv() got an unexpected keyword argument 'line_terminator'

Looking at the Traceback the keyword for line terminator should 'lineterminator'

Thanks

KNIME version: 4.7.7
Python: 3.9.18
Computer: MacBook Pro, M1 Max, 64GB RAM 
OS: Ventura 13.5.1

**Comment by niederle** [comment]
Thank you for pointing that out. Indeed, the argument 'line_terminator' changed to 'lineterminator' with pandas <=1.4 to pandas >= 2.0
I can confirm that the node works with pandas (1.4.4) using python 3.8 (which also work with python 3.9).

**Comment by bicklem** [comment]
Thank you for posting your pandas version, I could create an environment with all requested packages. The first scripts work now and return the tables just fine.

**Comment by niederle** [comment]
I will keep the issue open to take care of it as soon as there are capacities. The node should not depend too much on python package versions.

**Comment by marcbickle** [comment]
Hello,
I'm coming back to the issue of the line teminator of pandas. I need later versions of python for cellpose and would really need this backend to be updated. Is this going to be fixed or should I think of other solutions?

**Comment by niederle** [comment]
I will try to implement a blind fix this week. Which means, I will not have time to test whether it's working and it will be available only for you current KNIME version for now. Sorry, there are no capacities for deeper troubleshooting. 
Beside that: depending on multiple factors you might want to check out the possibilities to develop Python-based KNIME nodes (pure Python, seems rather easy to implement).

**Comment by marcbickle** [comment]
Hi, thank you for the feedback. Developing python-based KNIME nodes sounds great. Thank you for the tip, I will look into it
